stages:
  - build
  - test

typescript_build:
  stage: build
  script:
    - yarn install --ignore-engines
    - tsc -p ./tsconfig.json

lint:
  stage: test
  before_script:
    - yarn install --ignore-engines
  script:
    - yarn run lint-find

